export FZF_DEFAULT_OPTS="
  --bind=alt-j:preview-down,alt-k:preview-up,alt-d:preview-page-down,alt-u:preview-page-up,change:first,alt-a:select-all,alt-A:deselect-all,alt-p:toggle-preview \
  --preview-window=noborder \
  --layout=reverse \
  --highlight-line \
  --info=inline-right \
  --ansi \
  --border=none
  --color=bg+:8 \
  --color=bg:0 \
  --color=border:8 \
  --color=fg:7 \
  --color=fg+:15 \
  --color=gutter:0 \
  --color=header:5 \
  --color=hl+:6 \
  --color=hl:5 \
  --color=info:12 \
  --color=marker:2 \
  --color=pointer:4 \
  --color=prompt:3 \
  --color=query:7:regular \
  --color=scrollbar:4 \
  --color=separator:8 \
  --color=spinner:1 \
"
